# Generated by Django 4.0.6 on 2022-07-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyapp',
            old_name='edad',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='familyapp',
            name='nacimiento',
            field=models.CharField(max_length=40),
        ),
    ]
