# Generated by Django 4.0.6 on 2022-07-28 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyApp', '0002_rename_edad_familyapp_age_alter_familyapp_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyapp',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
