# Generated by Django 4.0.6 on 2022-07-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyApp', '0004_alter_familyapp_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyapp',
            name='nacimiento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
