# Generated by Django 4.0.6 on 2022-07-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyApp', '0005_alter_familyapp_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyapp',
            old_name='nacimiento',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='familyapp',
            old_name='nombre',
            new_name='name',
        ),
    ]
